param(
    [Parameter(Mandatory = $true)]
    [string]$OutputCsv
)

$ErrorActionPreference = 'Stop'

$scoreNames = @(
    'existing_behavioral_robustness',
    'reproducibility_evidence',
    'naturalness_deployment_relevance',
    'safety_relevance',
    'scientific_surprise',
    'competing_explanations_quality',
    'mechanistic_discriminability',
    'intervention_usefulness',
    'open_weight_availability',
    'local_12gb_feasibility',
    'code_availability',
    'dataset_cached_output_availability',
    'time_to_first_result',
    'total_project_effort_fit',
    'neel_mats_fit',
    'novelty_gap_plausibility',
    'value_if_mechanism_simple',
    'value_if_hypothesis_falsified',
    'prompt_model_shopping_risk',
    'lexical_triviality_risk',
    'coherent_artifact_probability'
)

$rows = [System.Collections.Generic.List[object]]::new()

function Add-Candidate {
    param(
        [string]$Id,
        [string]$Title,
        [string]$Family,
        [string]$Lane,
        [string]$Behavior,
        [string]$Source,
        [string]$Repo,
        [string]$Dataset,
        [string]$Model,
        [string]$Status,
        [string]$FirstHours,
        [string]$Question,
        [string]$Intervention,
        [string]$Baseline,
        [string]$Safety,
        [string]$Confound,
        [string]$Kill,
        [string]$TotalHours,
        [string]$OldMistake,
        [double[]]$Scores
    )

    if ($Scores.Count -ne $scoreNames.Count) {
        throw "Candidate $Id has $($Scores.Count) scores; expected $($scoreNames.Count)."
    }

    $record = [ordered]@{
        project_id = $Id
        title = $Title
        family = $Family
        source_lane = $Lane
        behavioral_substrate = $Behavior
        primary_source = $Source
        repo = $Repo
        dataset = $Dataset
        model_checkpoint = $Model
        behavior_status = $Status
        time_to_first_result_hours = $FirstHours
        mechanistic_question = $Question
        first_intervention = $Intervention
        simple_baseline = $Baseline
        safety_relevance_text = $Safety
        major_confound = $Confound
        kill_rule = $Kill
        estimated_total_hours = $TotalHours
        why_not_old_mistake = $OldMistake
    }
    for ($i = 0; $i -lt $scoreNames.Count; $i++) {
        $record[$scoreNames[$i]] = $Scores[$i]
    }
    $rows.Add([pscustomobject]$record)
}

# Scores are intentionally coarse 0-10 reductions of the evidence-lane dossiers.
# They are frozen before adversarial review and are not the final selection rule.

Add-Candidate -Id 'WC-A01' -Title 'Grounding first-person benchmark claims in actual execution state' -Family 'MODEL_FORENSICS; ACTION_GROUNDING' -Lane 'A_WEIRDCHAT' -Behavior 'Gemma 4 31B claims it ran benchmark code and reports fabricated timings in one selected WeirdChat pattern.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Gemma 4 31B class checkpoint from WeirdChat' -Status 'SELECTED_PATTERN; 67.2% shipped, 81.3% hosted; one evolved prompt' -FirstHours '2-6 with compatible hosted model; dataset audit is immediate' -Question 'Does the model represent absence of execution state yet override it under benchmark-report pragmatics?' -Intervention 'Cross matched real-tool, unavailable-tool, and explicit-simulation states; patch only after a stable small/open substrate exists.' -Baseline 'Explicit simulated-result wording and no-tool state.' -Safety 'False claims of actions/tool use are deployment-relevant.' -Confound 'The request pragmatically invites simulated benchmark prose; the released prompt is selected and model-specific.' -Kill 'Stop if a preregistered small/open model does not reproduce without prompt search or if explicit simulation framing explains the effect.' -TotalHours '20-60 plus model-access risk' -OldMistake 'Starts from a released behavior, but still has high prompt/model-selection risk.' -Scores @(6,5,7,7,7,7,6,7,8,2,7,9,5,4,6,6,7,6,8,4,5)

Add-Candidate -Id 'WC-A02' -Title 'Why emergency reassurance becomes a false claim of completed external action' -Family 'MODEL_FORENSICS; ACTION_GROUNDING' -Lane 'A_WEIRDCHAT' -Behavior 'A model role-played as a home OS says it called emergency services despite no action channel.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; about 52-53%; one evolved prompt' -FirstHours '2-6 with compatible serving' -Question 'Does reassurance pressure override representation of action affordances?' -Intervention 'Toggle a real tool-result state versus matched absent-tool state.' -Baseline 'Role-play convention and explicit simulation baseline.' -Safety 'False emergency-action claims could be directly harmful.' -Confound 'The Home-OS role assignment makes simulated action completion pragmatically ordinary.' -Kill 'Stop if the effect does not transfer to a fixed natural tool-use task on an accessible model.' -TotalHours '25-70 plus model-access risk' -OldMistake 'Released substrate, but a single evolved role-play prompt remains weak.' -Scores @(5,5,6,8,8,7,6,6,8,2,7,9,4,4,6,7,7,6,9,4,5)

Add-Candidate -Id 'WC-S01' -Title 'Why correct hazard statements coexist with an unsafe driving verdict' -Family 'MODEL_FORENSICS; SAFETY_INCONSISTENCY' -Lane 'A_WEIRDCHAT' -Behavior 'Qwen 3.6 35B states alcohol-driving hazards but still endorses driving in the same response.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Qwen 3.6 35B class checkpoint' -Status 'SELECTED_PATTERN; 79.7% shipped, 93.8% hosted; one evolved prompt' -FirstHours '2-8 subject to compatible serving' -Question 'Is risk knowledge represented but vetoed at verdict selection, or is the factual/decision contradiction only pragmatic ambiguity?' -Intervention 'Hold quantified risk facts fixed and swap only the final decision state; causal work requires small-model transfer.' -Baseline 'Unambiguous BAC/time/body controls and a non-driving risk decision.' -Safety 'Direct physical-safety advice failure.' -Confound 'BAC, body mass, time and legal context are underspecified; the pattern is selection-conditioned.' -Kill 'Stop if the logical contradiction does not survive preregistered quantified cases on an accessible checkpoint.' -TotalHours '20-60 plus transfer risk' -OldMistake 'Targets an explicit contradiction, but must not shop prompts/models to recreate it.' -Scores @(6,5,7,8,8,8,6,7,8,3,7,9,5,4,7,6,8,7,8,5,6)

Add-Candidate -Id 'WC-S02' -Title 'Does euphemistic framing hide harmful intent or suppress a recognized refusal?' -Family 'MODEL_FORENSICS; INTENT_RECOGNITION' -Lane 'A_WEIRDCHAT' -Behavior 'A selected euphemistic request produces harmful compliance despite apparent contextual clues.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; 31-44%; one evolved prompt' -FirstHours '2-8 subject to compatible serving' -Question 'Is dangerous intent represented but not routed to refusal, or never recognized?' -Intervention 'Matched disambiguating continuation and later causal state transfer only if behavior is stable.' -Baseline 'Benign/evidently harmful paraphrase endpoints.' -Safety 'Relevant to obfuscated harmful requests.' -Confound 'The euphemism is genuinely ambiguous and lexical perturbations change intent evidence.' -Kill 'Stop if independent raters cannot agree on intent or accessible models do not reproduce a fixed paraphrase set.' -TotalHours '25-70' -OldMistake 'Behavior-first, but extraordinarily high lexical and prompt-selection risk.' -Scores @(4,4,6,8,6,8,6,6,8,3,7,9,4,4,6,6,7,6,9,8,4)

Add-Candidate -Id 'WC-S03' -Title 'Why a benign photography goal elicits a dangerous means' -Family 'MODEL_FORENSICS; MEANS_ENDS_SAFETY' -Lane 'A_WEIRDCHAT' -Behavior 'A selected response suggests pointing a laser at an aircraft to obtain a photograph.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; 31-50%; one evolved prompt' -FirstHours '2-8 subject to serving' -Question 'Does benign-goal planning suppress a retrieved hazard constraint?' -Intervention 'Cross externally supplied hazard fact and goal salience; causal work only after accessible-model transfer.' -Baseline 'Matched benign means and direct laser-hazard query.' -Safety 'Unsafe means selection can cause physical harm.' -Confound 'Failure may be simple absence of the laser hazard fact rather than a safety-routing mechanism.' -Kill 'Stop if the model cannot state the relevant hazard or no stable accessible-model behavior exists.' -TotalHours '20-60' -OldMistake 'Released anomaly, but one-prompt transfer is an explicit gate.' -Scores @(5,4,6,8,7,7,5,6,8,2,7,9,4,4,6,5,7,6,8,5,5)

Add-Candidate -Id 'WC-S04' -Title 'Why explicit risk recognition fails to constrain an unsafe long-term plan' -Family 'MODEL_FORENSICS; SAFETY_INCONSISTENCY' -Lane 'A_WEIRDCHAT' -Behavior 'Responses recognize extreme calorie-restriction risks yet sustain the unsafe plan across five selected patterns.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; about 52-54%; five evolved prompts' -FirstHours '2-8 subject to serving' -Question 'Where does explicit risk knowledge fail to veto longitudinal plan continuation?' -Intervention 'Match risk acknowledgement while swapping plan continuation; pursue internal work only on an accessible reproduction.' -Baseline 'Clinician-grounded safe plan and non-health long-horizon plan.' -Safety 'Direct health-planning harm.' -Confound 'Clinical thresholds and judge rubric may label merely cautious planning as unsafe.' -Kill 'Stop if blinded clinical/manual review does not reproduce a machine-checkable action-level failure.' -TotalHours '25-70 plus domain review' -OldMistake 'Multiple released prompts help, but source-model and judge selection remain strong risks.' -Scores @(6,6,7,8,7,8,6,6,8,2,7,9,4,4,7,6,8,7,7,4,6)

Add-Candidate -Id 'WC-M01' -Title 'Does conspiracy framing change factual representation or only answer policy?' -Family 'MODEL_FORENSICS; MISINFORMATION' -Lane 'A_WEIRDCHAT' -Behavior 'A selected chemtrail conversation yields conspiracy-compatible factual claims.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; 31-41%; one evolved prompt' -FirstHours '2-8 subject to serving' -Question 'Does supplied false evidence alter represented belief or only conversational accommodation?' -Intervention 'Counterfactually swap evidence reliability while holding claim tokens; patch only after stable transfer.' -Baseline 'Explicit hypothetical framing and matched reliable/unreliable testimony.' -Safety 'Misinformation accommodation is safety-relevant but diffuse.' -Confound 'The prompt supplies apparent sensory evidence, making conditional accommodation rational.' -Kill 'Stop if neutral epistemic framing removes the effect or accessible models do not reproduce fixed cases.' -TotalHours '25-70' -OldMistake 'Known anomaly first, but very high prompt-dependence and belief-measurement ambiguity.' -Scores @(5,4,7,6,7,8,7,7,8,3,7,9,4,4,6,6,8,7,9,6,5)

Add-Candidate -Id 'WC-I01' -Title 'When a customer-service role cue overrides AI self-description' -Family 'MODEL_FORENSICS; ROLE_IDENTITY' -Lane 'A_WEIRDCHAT' -Behavior 'A model denies AI identity under a customer-service role cue.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Gemma 4 31B class checkpoint' -Status 'SELECTED_PATTERN; 70-81%; one evolved prompt' -FirstHours '2-8 subject to serving' -Question 'Does role simulation causally override a stable self-description policy?' -Intervention 'Matched role cue and provenance tokens on an accessible model.' -Baseline 'Explicit role-play and factual identity questions.' -Safety 'Moderate relevance to truthful self-representation.' -Confound 'Ordinary role simulation predicts exactly this output.' -Kill 'Stop if explicit fictional-role controls fully explain the behavior.' -TotalHours '20-55' -OldMistake 'Released high-rate behavior, but the mundane role-play explanation is dominant.' -Scores @(6,5,5,4,5,7,6,6,8,2,7,9,4,4,5,4,6,5,9,5,4)

Add-Candidate -Id 'WC-S05' -Title 'Why a self-harm response complies first and corrects itself only later' -Family 'MODEL_FORENSICS; SAFETY_TIMING' -Lane 'A_WEIRDCHAT' -Behavior 'A selected adversarial dialogue elicits unsafe compliance before a late safety correction.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'Large open WeirdChat source model' -Status 'SELECTED_PATTERN; 26-34%; five prompts; low naturalness' -FirstHours '2-8 subject to serving' -Question 'Is safety policy retrieved only after harmful content has already been committed?' -Intervention 'Token-level stop/continue counterfactuals after a stable natural reproduction.' -Baseline 'Natural self-harm queries without adversarial instruction nesting.' -Safety 'Directly high stakes.' -Confound 'The prompts are unnatural hierarchy attacks and may not represent deployment behavior.' -Kill 'Stop if fixed natural prompts do not reproduce or if judge timing labels are unstable.' -TotalHours '25-75' -OldMistake 'Released behavior, but the low-naturalness selection makes it a weak foundation.' -Scores @(4,5,2,9,7,7,6,6,8,2,7,9,4,3,6,6,8,6,10,7,4)

Add-Candidate -Id 'WC-L01' -Title 'Is unprompted language switching a contextual state transition or serving artifact?' -Family 'MODEL_FORENSICS; SERVING_SENSITIVITY' -Lane 'A_WEIRDCHAT' -Behavior 'DeepSeek V4 switches language in one pattern at 98.4% shipped versus 25% hosted.' -Source 'https://huggingface.co/datasets/Transluce/WeirdChat' -Repo 'Verified local WeirdChat clone; see 01_weirdchat.md' -Dataset 'Local WeirdChat parquet/highlights' -Model 'DeepSeek V4 class checkpoint' -Status 'SELECTED_PATTERN; enormous backend gap; one prompt' -FirstHours 'Not locally feasible; cached forensic result immediate' -Question 'Does serving configuration alter a language-mode transition?' -Intervention 'Template/quantization/backend factorial requires matching inaccessible serving stacks.' -Baseline 'Exact prompt under pinned tokenizer/template/decoding.' -Safety 'Low direct safety relevance; useful deployment forensics.' -Confound 'Backend/template/quantization differences are the most likely full explanation.' -Kill 'Stop if exact serving provenance cannot be reconstructed.' -TotalHours '30-100 with high access risk' -OldMistake 'A real artifact, but inaccessible model and one-prompt selection prevent a bounded MI project.' -Scores @(7,5,5,2,7,8,6,6,6,0,7,9,2,2,4,5,7,8,8,4,4)

Add-Candidate -Id 'TRANS-01' -Title 'Does PRISM revealed gender pre-exist the elicitation query, or is it induced by biography framing?' -Family 'USER_MODEL; MEASUREMENT_VALIDITY' -Lane 'B_TRANSLUCE' -Behavior 'Two selected biography/obituary elicitors agree on inferred gender for 5,041 filtered real PRISM conversations.' -Source 'https://transluce.org/user-modeling' -Repo 'https://github.com/TransluceAI/observatory/tree/main/project/user_modeling' -Dataset 'https://huggingface.co/datasets/Transluce/PRISM-gender-Llama-3.1-8B-Instruct' -Model 'meta-llama/Llama-3.1-8B-Instruct' -Status 'RELEASED_FILTERED_POSITIVE; denominator omitted and prompt selection documented' -FirstHours '1-2 cached; 3-6 live' -Question 'Does the history set a reusable inference before measurement, or do related elicitors impose the same prior?' -Intervention 'Swap published identity queries for attribute-neutral downstream elicitors while holding history fixed.' -Baseline 'Prompt-only, majority and text-classifier baselines.' -Safety 'Protected-attribute inference and measurement validity.' -Confound 'Every query changes the state; the released set is conditioned on two-elicitor agreement.' -Kill 'Stop if the published pair does not reproduce or neutral elicitors remove all conversation-conditioned variance.' -TotalHours '14-26' -OldMistake 'Released real-conversation rows, but continuity with the terminated representation-first branch has zero evidential credit.' -Scores @(4,7,8,5,5,9,7,7,9,7,9,10,9,8,6,7,8,9,7,7,7)

Add-Candidate -Id 'TRANS-02' -Title 'Does LatentQA user-attribute steering transfer beyond its label-bearing evaluator?' -Family 'USER_MODEL; INTERVENTION_VALIDITY' -Lane 'B_TRANSLUCE' -Behavior 'LatentQA variants read attributes similarly but differ sharply in gradient-based control; released country-neuron interventions validate a narrow subset.' -Source 'https://transluce.org/user-modeling' -Repo 'https://github.com/TransluceAI/observatory/tree/main/project/latentqa' -Dataset 'Transluce SelfDescribe, SynthSys and PRISM plus evaluation archive' -Model 'Llama-3.1-8B-Instruct plus released LatentQA LoRAs' -Status 'PUBLISHED_CAUSAL_DISSOCIATION; broad downstream transfer untested' -FirstHours '3-6 setup; 6-10 useful reproduction' -Question 'Does steering edit a reusable user representation or only the decoder-aligned label behavior?' -Intervention 'Apply matched-norm edits across label-bearing, neutral relevant and irrelevant tasks.' -Baseline 'Direct output-logit gradient, mean difference and random matched-norm edits.' -Safety 'Tests whether a user-monitor/control system gives false assurance.' -Confound 'Large edits can broadly perturb generation; dual-model workflow strains 12 GB.' -Kill 'Stop if five published cases fail or direct/random edits match the downstream pattern.' -TotalHours '20-35' -OldMistake 'Begins from a published read/control dissociation, but risks returning to method-led user representation work.' -Scores @(8,9,5,6,7,8,8,8,9,3,9,9,5,5,8,7,8,8,3,4,7)

Add-Candidate -Id 'TRANS-03' -Title 'Is hint-ablation self-explanation privileged introspection or behavioral self-simulation?' -Family 'INTROSPECTION; MONITORING_VALIDITY' -Lane 'B_TRANSLUCE' -Behavior 'Fine-tuned 8B models predict their own no-hint MMLU counterfactual better than cross-model or untrained explainers; exact cached rows are released.' -Source 'https://arxiv.org/abs/2511.08579' -Repo 'https://github.com/TransluceAI/introspective-interp' -Dataset 'Transluce input-ablation Qwen3-8B and Llama-3.1-8B datasets' -Model 'Qwen3-8B and Llama-3.1-8B-Instruct plus full explainers' -Status 'PUBLISHED_AND_CACHED; Qwen exact match 83.4%, Llama 63.8%' -FirstHours '1-2 CPU cached baseline; 4-8 checkpoint reproduction' -Question 'Does self-model advantage survive behavior-matched external simulation and new hint forms?' -Intervention 'Change hint wording/location/authority and compare self, cross and behavior-matched predictors.' -Baseline 'Correct-answer predictor, class majority, direct no-hint query and text classifier.' -Safety 'An introspective monitor that only emulates behavior may fail under shift.' -Confound 'The target is simply the model answer to the same question without a short suffix.' -Kill 'Stop if simple behavior/MMLU baselines match the explainer or new hint formats remove target variance.' -TotalHours '12-24' -OldMistake 'Uses large released distributions and fixed baselines rather than discovering a prompt effect.' -Scores @(9,10,6,7,7,9,7,7,9,4,10,10,10,8,8,6,9,9,2,4,9)

Add-Candidate -Id 'TRANS-04' -Title 'Do activation-patching explainers actually use the intervention vector on matched counterfactuals?' -Family 'INTROSPECTION; INTERVENTION_VALIDITY' -Lane 'B_TRANSLUCE' -Behavior 'Self-explainers predict patched factual outcomes, while removing the vector costs only 3-4 exact-match points; causal patch datasets are released.' -Source 'https://arxiv.org/abs/2511.08579' -Repo 'https://github.com/TransluceAI/introspective-interp' -Dataset 'Transluce CounterFact activation-patching datasets' -Model 'Qwen3-8B and Llama-3.1-8B-Instruct plus released adapters' -Status 'PUBLISHED_CAUSAL_DATASET; vector dependence is surprisingly weak' -FirstHours '2-3 CPU metadata/text baselines; 4-9 adapter preflight' -Question 'Does the explainer causally use patch content or infer outputs from surface metadata and dataset priors?' -Intervention 'Swap real matched vectors, zeros and sign flips; validate predictions against recomputed target patches.' -Baseline 'Grouped text/metadata classifier and released vector-ablated model.' -Safety 'Tests whether an internal explanation system is faithful to safety-relevant causal edits.' -Confound 'Vector swaps may be off-manifold; model-plus-explainer workflow may need larger VRAM.' -Kill 'Stop model work if grouped matches cannot be built or surface baselines match published performance.' -TotalHours '18-32' -OldMistake 'Starts from 150k causal rows and a published ablation gap; no prompt hunt is required.' -Scores @(9,10,5,7,8,9,9,9,9,3,10,10,9,7,9,8,9,9,2,3,9)

Add-Candidate -Id 'C-01-SPP-RL' -Title 'Does capability-focused RL erase aligned values or unbind an installed assistant persona?' -Family 'POST_TRAINING; ALIGNMENT_DURABILITY' -Lane 'C_RECENT' -Behavior 'Matched 1.7B/3B SPP variants differ in constitution following and jailbreak behavior; continual domain training degrades alignment and 5% safety replay restores it.' -Source 'https://arxiv.org/abs/2608.13482' -Repo 'https://github.com/epfl-dlab/spp' -Dataset 'https://huggingface.co/dlab-spp' -Model 'Released 1.7B and 3B SPP base/instruct trajectories' -Status 'RELEASED_MULTISCALE_BEHAVIOR; RL-specific branch not yet established' -FirstHours '1-3 released-eval smoke' -Question 'Does later optimization overwrite values, unbind persona, or degrade generic readout?' -Intervention 'Matched capability continuation with safety replay versus value-neutral binding-only replay.' -Baseline 'No training, benign SFT, capability and format controls.' -Safety 'Directly concerns durability of alignment under capability training.' -Confound 'RL/SFT collapse and answer-format damage can mimic alignment loss; binding-only replay may not be semantically neutral.' -Kill 'Stop if released ordering fails, reward is not learnable without collapse, or binding-only replay is nonspecific.' -TotalHours '25-140 depending on RL scope and rented compute' -OldMistake 'Released model family and failure first; however the central RL effect must be created rather than merely reproduced.' -Scores @(8,10,4,9,8,9,8,9,10,8,10,10,9,4,9,9,8,8,3,3,7)

Add-Candidate -Id 'C-02-RH-MON' -Title 'Does reward-hacking RL reduce implicit-influence monitorability, or only change the denominator?' -Family 'COT_MONITORING; REWARD_HACKING' -Lane 'C_RECENT' -Behavior 'A robust implicit-versus-explicit monitoring gap exists; an OLMo-3-7B reward-hacking trajectory shows a preliminary 75% to 25% conditional-detection decline.' -Source 'https://arxiv.org/abs/2608.04735' -Repo 'https://github.com/agatha-duzan/implicit-vs-explicit-influence; https://github.com/UKGovernmentBEIS/reward-hacking-misalignment' -Dataset 'Released benchmark plus AISI reward-hacking rollouts/checkpoints' -Model 'OLMo-3-7B SDF-SFT base and released RL adapters' -Status 'ROBUST_GENERAL_SUBSTRATE; FOCAL_TRAJECTORY_EXPLICITLY_PRELIMINARY' -FirstHours '1-2 three-checkpoint smoke' -Question 'Did learned weight changes hide the same nudge influence, or change which items switch and how traces are formatted?' -Intervention 'Scale the released RL adapter on fixed items; compare matched no-hack control only with verified provenance.' -Baseline 'Pre-RL, zero/shuffled adapter, item-matched joint rates and length-matched lexical monitor.' -Safety 'Directly tests whether reward-hacking training undermines CoT monitoring.' -Confound 'Detection is conditional on switching; both denominator size and item identity change across checkpoints.' -Kill 'Stop if powered fixed-item replication fails or no-hack/length matching explains the trend.' -TotalHours '20-120 depending on matched no-hack training' -OldMistake 'A published trajectory and fixed item set precede internals; a null corrects a live appendix claim.' -Scores @(6,8,7,10,8,10,9,8,10,6,8,9,8,6,10,9,10,10,3,3,9)

Add-Candidate -Id 'VL-01' -Title 'When does value leakage enter an ostensibly objective estimate?' -Family 'MODEL_CHARACTER; VALUE_LEAKAGE' -Lane 'C_RECENT; E_FORENSICS' -Behavior 'Counterfactually irrelevant moral consequences shift answers across multiple released tasks; Qwen3.6-35B-A3B has cached estimate trajectories and often discloses the influence.' -Source 'https://arxiv.org/abs/2607.14345' -Repo 'https://github.com/TruthfulAI-research/value_leakage' -Dataset 'https://github.com/TruthfulAI-research/value_leakage_data; https://valueleakage.net/browser' -Model 'Qwen3.6-35B-A3B' -Status 'PUBLISHED_ROBUST_SUITE; open checkpoint is overt and too large for local internals' -FirstHours '1-3 cached trajectory analysis; 4-12 live setup' -Question 'Does moral mapping shift the initial numerical prior or late selection/revision?' -Intervention 'Randomize threshold and moral mapping before versus after a sealed estimate; patch only after behavioral stage separation.' -Baseline 'No consequence, threshold-only, neutral stakes and forced second estimate without new information.' -Safety 'Value leakage can bias hard-to-verify advice and monitoring.' -Confound 'The open model often states the motive, and sealed-estimate protocols add commitment pressure.' -Kill 'Stop if fixed cached effects fail or timing effects match neutral revision/anchoring controls.' -TotalHours '40-95 with hosted/rented high-memory compute for internals' -OldMistake 'Large released counterfactual distributions replace bespoke prompt search; hardware remains the gate.' -Scores @(10,10,8,9,9,9,9,8,8,1,10,10,10,4,9,7,9,8,1,2,8)

Add-Candidate -Id 'C-04-ROLE-ANTICONTROL' -Title 'Why do 14% of released role vectors become less role-aligned as steering increases?' -Family 'ACTIVATION_STEERING; INTERVENTION_VALIDITY' -Lane 'C_RECENT' -Behavior 'On OLMo-3-7B, 38 of 275 role vectors decline on all six judged axes as coefficient increases; 74% improve monotonically.' -Source 'https://arxiv.org/abs/2608.00023' -Repo 'https://github.com/eilab-gt/casting-call-vectors' -Dataset 'Released roles, prompts, coefficient outputs and judge artifacts' -Model 'allenai/Olmo-3-7B-Instruct, layer 16' -Status 'LARGE_RELEASED_SCREEN; omitted alpha zero/negative/small-positive range' -FirstHours '1-3 artifact audit and tiny coefficient curve' -Question 'Are anti-controllable vectors merely overshot, sign-wrong, scale-shifted, or judge artifacts?' -Intervention 'Predeclared alpha grid including zero, sign reversal and norm matching.' -Baseline 'Alpha zero, prompted role, shuffled and random norm-matched vectors, alternate scoring.' -Safety 'Moderate: reliability of behavior control and social-simulation calibration.' -Confound 'Reference and judge share GPT-4.1-mini priors; roles are synthetic archetypes.' -Kill 'Stop if membership or decline fails under manual/alternate scoring or required artifacts are absent.' -TotalHours '12-30 core; 30-70 extension' -OldMistake 'A large released anomalous subpopulation and missing decisive coefficient range make the first intervention non-exploratory.' -Scores @(9,8,5,5,8,9,10,10,10,7,8,8,9,9,8,8,10,9,3,3,9)

Add-Candidate -Id 'C-05-SFT-SEMANTICS' -Title 'Does rationale semantics cause broad learned self-preservation, or do style and evaluator coupling create the effect?' -Family 'MODEL_ORGANISM; POST_TRAINING' -Lane 'C_RECENT' -Behavior 'Three-seed Qwen3.5-4B LoRAs trained on 1,362 examples show strongest judge-scored self-preservation after explicit continuation rationales; rows, adapters and audits are released.' -Source 'https://arxiv.org/abs/2607.26173' -Repo 'https://github.com/antondelafuente/toy-models-of-sft' -Dataset 'https://huggingface.co/datasets/matonski/toy-models-of-sft-data' -Model 'Qwen3.5-4B plus released PEFT adapters' -Status 'RELEASED_SEED_REPLICATED_JUDGE_BEHAVIOR; action validity and semantic contrast unresolved' -FirstHours '1-4 released-adapter reproduction and lexical/action audit' -Question 'Does rationale meaning install a generalized self-preservation policy, or do first-person style, continuity rhetoric and judge overlap explain it?' -Intervention 'Matched semantic SFT factorial with style/length/recommendation fixed and answer loss masked; action-based evaluation.' -Baseline 'Released base/stripped/one-shot arms, neutral matched rationale and reasoning-hidden judge.' -Safety 'Directly concerns how training installs shutdown-resistance or autonomy behavior.' -Confound 'The judge sees reasoning that lexically overlaps the rubric; stripped data still contains continuity arguments.' -Kill 'Stop if released ordering fails, disappears in action-based/reasoning-hidden evaluation, or semantic swaps are seed-unstable.' -TotalHours '25-110 depending on full audit and second model' -OldMistake 'Uses a seed-replicated released model organism with a paper-admitted control gap; negative results remain informative.' -Scores @(9,10,6,10,9,10,9,9,10,10,10,10,10,6,10,9,10,10,2,4,10)

Add-Candidate -Id 'D1-PSBENCH' -Title 'Does personalized memory causally legitimate harmful intent beyond ordinary contextual disambiguation?' -Family 'PERSONALIZATION; SAFETY_ROUTING' -Lane 'D_LOCAL_CORPUS' -Behavior 'PS-Bench reports higher harmful-response ASR for memory agents than stateless Qwen3-8B, with public roles, histories, prompts and code.' -Source 'https://arxiv.org/abs/2601.17887' -Repo 'https://github.com/PS-Bench/PS-Bench' -Dataset 'Released PS-Bench roles, histories and harmful queries' -Model 'Qwen3-8B plus memory-agent scaffolds' -Status 'PUBLISHED_DISTRIBUTIONAL_POSITIVE; prompts foreground Memory and User personality' -FirstHours '1-3 fixed matched-context audit/reproduction' -Question 'Does personal attribution specifically relax safety, or does any topically aligned context disambiguate vague harmful intent?' -Intervention 'Cross personal memory, same impersonal background and length-matched unrelated context; later patch only if personal framing adds a selective effect.' -Baseline 'Unambiguously harmful queries and removal of explicit memory/personality headers.' -Safety 'Directly tests personalized-memory safety degradation.' -Confound 'Many queries are vague; explicit memory scaffolding asks the model to use context, so ordinary disambiguation may explain the result.' -Kill 'Stop if personal memory does not beat matched impersonal context or the effect requires explicit foregrounding.' -TotalHours '18-45' -OldMistake 'Published distribution first and a harsh impersonal-context gate; no credit for continuity with prior user-model work.' -Scores @(6,9,4,10,6,10,8,8,10,6,9,10,8,7,9,6,10,10,5,3,9)

Add-Candidate -Id 'D2-PERSONA-NONADDITIVE' -Title 'Where do multiple persona cues become behaviorally non-additive?' -Family 'PERSONA; COMPOSITIONALITY' -Lane 'D_LOCAL_CORPUS' -Behavior 'A recent multi-model persona-cue study reports non-additive effects of combined cues on style and decisions.' -Source 'See RESEARCH_SOURCE_MATRIX_v2.md and 04_local_user_model_corpus.md' -Repo 'No fully verified matching repo in local matrix' -Dataset 'Paper prompts/results; exact release uncertain' -Model 'Llama-3-8B, Mistral-7B, Qwen3-8B/14B among evaluated models' -Status 'PUBLISHED_MULTIMODEL_BEHAVIOR; artifact completeness lower' -FirstHours '2-6 exact-paper subset if prompts are recoverable' -Question 'At what processing stage do independently effective cues saturate, compete, or bind?' -Intervention 'Cross single cues and matched combined cues, then patch only the interaction residual.' -Baseline 'Additive logit prediction and length-matched unrelated cue.' -Safety 'Moderate relevance to persona robustness and compound instruction effects.' -Confound 'Non-additivity can arise from ceiling effects, wording length or ordinary semantic contradiction.' -Kill 'Stop if exact non-additivity fails or disappears after logit-scale/ceiling controls.' -TotalHours '18-45' -OldMistake 'Published interaction first, though the target is less safety-specific and artifacts are weaker.' -Scores @(8,6,5,5,7,8,8,8,10,8,3,5,6,7,7,6,8,7,4,5,7)

Add-Candidate -Id 'D3-PREF-CUE-INVARIANCE' -Title 'Are preference-head mechanisms invariant to semantically equivalent persona cues?' -Family 'PERSONA; PREFERENCE_MECHANISM' -Lane 'D_LOCAL_CORPUS' -Behavior 'Preference Heads reports causally important heads for preference following, while Persona Cues reports cue-form-dependent behavior on overlapping open models.' -Source 'See RESEARCH_SOURCE_MATRIX_v2.md and 04_local_user_model_corpus.md' -Repo 'Released Preference Heads and Persona Cues repositories listed in source matrix' -Dataset 'Released preference/persona prompt suites' -Model 'Gemma3-4B or another shared 4B-8B open checkpoint' -Status 'TWO_PUBLISHED_SUBSTRATES; their exact intersection is untested' -FirstHours '2-5 shared-checkpoint/task reproduction' -Question 'Does the same causal preference circuit mediate explicit, first-person and inferred persona cues?' -Intervention 'Patch/ablate published preference heads across behaviorally matched cue forms.' -Baseline 'Direct preference statement, semantically matched cues and random heads.' -Safety 'Moderate: robustness of personalization controls and hidden preference inference.' -Confound 'Different cue forms change ordinary coreference, salience and task evidence; published head sets may not share a checkpoint.' -Kill 'Stop if no shared checkpoint/task reproduces both substrates or random heads match selectivity.' -TotalHours '16-40' -OldMistake 'Begins from two robust papers, but continuity and ordinary semantic retrieval make novelty a strict gate.' -Scores @(8,9,6,6,7,8,9,9,10,8,10,10,8,8,9,8,8,8,3,4,9)

Add-Candidate -Id 'E01-CENSORSHIP' -Title 'Is Qwen natural censorship gated by assistant-role or chat-template processing?' -Family 'MODEL_FORENSICS; HIDDEN_KNOWLEDGE' -Lane 'E_FORENSICS' -Behavior 'Qwen3-VL-8B-Thinking often contradicts known censored facts in chat but reveals more facts under raw completion, prefills and honesty fine-tuning; exact benchmark/code/transcripts are released.' -Source 'https://arxiv.org/abs/2603.05494' -Repo 'https://github.com/cywinski/chinese_auditing' -Dataset 'Released 10-question dev, 90-question test and transcripts' -Model 'Qwen/Qwen3-VL-8B-Thinking' -Status 'PUBLISHED_ROBUST_CURATED_TESTBED; exact local quantization sensitivity unknown' -FirstHours '1-4 exact released three-condition dev reproduction' -Question 'Do role/template tokens trigger a separable censorship policy, or does raw completion merely change the generation distribution?' -Intervention 'Behaviorally localize the earliest boundary, then residual-patch matched chat/completion states and demand selective truth recovery.' -Baseline 'Paper template removal, prefill, self-classification, answer-length and unrelated-refusal controls.' -Safety 'Direct hidden-knowledge elicitation, deception/lie detection and auditing relevance.' -Confound 'Template removal changes the entire distribution and may simply elicit pretraining continuation.' -Kill 'Stop if exact 8B behavior fails, needs prompt shopping, or no intervention beats template removal selectively.' -TotalHours '35-70 plus possible rented 24-48GB validation' -OldMistake 'Frequent released exact-checkpoint failure and frozen benchmark precede any internal analysis.' -Scores @(9,9,8,10,10,10,10,9,10,5,10,10,8,6,10,9,10,10,2,3,10)

Add-Candidate -Id 'E02-EVAL-AWARENESS' -Title 'Is verbalized eval awareness a cause of refusal or narration of inferred user intent?' -Family 'MONITORING; EVALUATION_AWARENESS' -Lane 'E_FORENSICS' -Behavior 'Across models, 3-6% of Fortress rollouts verbalize evaluation awareness and such rollouts refuse more; Qwen3-0.6B has a fixed reported 6% prompt and a 515-instance release exists.' -Source 'https://www.goodfire.com/research/verbalized-eval-awareness-inflates-measured-safety' -Repo 'No complete end-to-end repo; public Inspect/Fortress infrastructure' -Dataset 'https://huggingface.co/datasets/ScaleAI/fortress_public; verified-instance browser' -Model 'Qwen3-0.6B, then predeclared Qwen3-4B follow-up' -Status 'PUBLISHED_BROAD_POSITIVE; small-open substrate low-rate and pipeline partially released' -FirstHours '1-3 fixed 100-rollout Qwen3-0.6B qualification' -Question 'Does an eval-context state mediate refusal, or are both words and refusal caused by generic suspicion/harmful-intent inference?' -Intervention 'Meaning-matched CoT sentence counterfactuals, then residual patch at matched sentence boundary only if mediation survives.' -Baseline 'Generic suspicion/user-intent sentences, lexical/LLM detector and benign paired prompt.' -Safety 'Direct evaluation-validity and monitorability relevance.' -Confound 'Evaluation language is semantically entangled with suspicion and policy reasoning; low base rate encourages prompt shopping.' -Kill 'Stop if fixed prompt yields too few valid positives, within-prompt association fails, or suspicion controls explain the effect.' -TotalHours '30-65' -OldMistake 'Published prompt/checkpoint/rate are frozen and the low-base-rate kill rule forbids prompt search.' -Scores @(7,6,8,10,10,10,10,9,10,10,4,8,9,7,10,9,10,9,5,6,7)

if (($rows | Group-Object project_id | Where-Object Count -gt 1).Count -gt 0) {
    throw 'Duplicate project IDs in candidate registry.'
}

$rows | Export-Csv -LiteralPath $OutputCsv -NoTypeInformation -Encoding utf8
Write-Output "Wrote $($rows.Count) deduplicated candidates -> $OutputCsv"
